# 2. NumPy

**NumPy** is a powerful set of tools to perform mathematical operations of on lists of numbers. It works faster than normal python lists operations and can manupilate high dimentional arrays too.

# Importing the Library

In [1]:
import numpy as np

## np.arange(start, stop, step, dtype = "None")

In [2]:
array_1 = np.arange(1,10, 0.2)

In [3]:
array_1.ndim

1

In [4]:
array_1.shape

(45,)

In [5]:
array_1.dtype

dtype('float64')

### Multidimensional Array

In [6]:
array_2 = np.array([[1,2],[3,4],[5,6]])

In [7]:
array_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
array_2.ndim

2

In [9]:
np.zeros((2,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [11]:
array_3 = np.linspace(1,5)

In [12]:
array_3.ndim

1

In [13]:
array_3

array([ 1.        ,  1.08163265,  1.16326531,  1.24489796,  1.32653061,
        1.40816327,  1.48979592,  1.57142857,  1.65306122,  1.73469388,
        1.81632653,  1.89795918,  1.97959184,  2.06122449,  2.14285714,
        2.2244898 ,  2.30612245,  2.3877551 ,  2.46938776,  2.55102041,
        2.63265306,  2.71428571,  2.79591837,  2.87755102,  2.95918367,
        3.04081633,  3.12244898,  3.20408163,  3.28571429,  3.36734694,
        3.44897959,  3.53061224,  3.6122449 ,  3.69387755,  3.7755102 ,
        3.85714286,  3.93877551,  4.02040816,  4.10204082,  4.18367347,
        4.26530612,  4.34693878,  4.42857143,  4.51020408,  4.59183673,
        4.67346939,  4.75510204,  4.83673469,  4.91836735,  5.        ])

np.linspace(start,stop, num = 50, endpoint = True )

In [14]:
matrix = np.random.random((2,3))

In [15]:
matrix

array([[ 0.51894351,  0.82956264,  0.29757728],
       [ 0.49700056,  0.09226748,  0.62737561]])

In [16]:
np.max(matrix)

0.82956264087207465

In [17]:
np.min(matrix)

0.09226748331248158

In [18]:
np.mean(matrix)

0.47712118066879672

In [21]:
np.median(matrix)

0.50797203573893146

In [22]:
np.std(matrix)

0.23426624941631569

In [23]:
np.sum(matrix)

2.8627270840127803

In [24]:
matrix.ndim

2

In [25]:
np.reshape(matrix, (3,2))

array([[ 0.51894351,  0.82956264],
       [ 0.29757728,  0.49700056],
       [ 0.09226748,  0.62737561]])

In [26]:
np.reshape(matrix, (6,1))

array([[ 0.51894351],
       [ 0.82956264],
       [ 0.29757728],
       [ 0.49700056],
       [ 0.09226748],
       [ 0.62737561]])

### Slicing 

In [27]:
df = np.random.random((5,10))

In [28]:
df

array([[ 0.29694936,  0.5180752 ,  0.4525742 ,  0.95897512,  0.35931305,
         0.28979451,  0.05575833,  0.74881299,  0.59363632,  0.78473026],
       [ 0.67827812,  0.30251061,  0.66836125,  0.83313478,  0.34391552,
         0.160502  ,  0.9018876 ,  0.97479407,  0.01766024,  0.07469562],
       [ 0.89394393,  0.99806776,  0.52303058,  0.54527377,  0.74766008,
         0.18619623,  0.81203591,  0.59170801,  0.44853896,  0.82666125],
       [ 0.53323813,  0.07015889,  0.995795  ,  0.713836  ,  0.24290295,
         0.76051736,  0.42941991,  0.99579789,  0.16258465,  0.45350666],
       [ 0.90654723,  0.23793734,  0.77636207,  0.5737801 ,  0.94940924,
         0.5467552 ,  0.48061241,  0.26400337,  0.75983349,  0.89269325]])

In [29]:
df[1]

array([ 0.67827812,  0.30251061,  0.66836125,  0.83313478,  0.34391552,
        0.160502  ,  0.9018876 ,  0.97479407,  0.01766024,  0.07469562])

In [30]:
df[0]

array([ 0.29694936,  0.5180752 ,  0.4525742 ,  0.95897512,  0.35931305,
        0.28979451,  0.05575833,  0.74881299,  0.59363632,  0.78473026])

In [31]:
df[0][1]

0.5180752033489523

In [32]:
df[0][0]

0.29694935668042366